import React from 'react';
import { Platform } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import {
  LayoutGrid,
  ShoppingCart,
  Receipt,
  Users,
  Package,
  FolderOpen,
  Tag,
  BarChart3,
  Wallet,
  UserCircle,
  Settings,
  Shield,
  Gift,
  HelpCircle,
  ChevronRight,
  LogOut,
  Store,
  Mail,
  Lock,
  Eye,
  EyeOff,
  AlertCircle,
  ArrowRight,
  CheckCircle,
  X,
  Globe,
  Calendar,
  FileText,
  Bell,
  Search,
  Plus,
  Minus,
  Trash2,
  Edit,
  MoreHorizontal,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  Home,
  TrendingUp,
  TrendingDown,
  DollarSign,
  CreditCard,
  Smartphone,
  Clock,
  Layers,
  Heart,
  Star,
  Share2,
  Copy,
  ExternalLink,
  Info,
  Zap,
  Send,
  MessageSquare,
  Phone,
  MapPin,
  Building,
  Briefcase,
  Printer,
  Download,
  Upload,
  Refresh,
  Filter,
  Grid,
  List,
  MoreVertical,
  Menu,
  XCircle,
  PlusCircle,
  MinusCircle,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  Percent,
  Hash,
  AtSign,
  Link,
  Paperclip,
  Image,
  Camera,
  Video,
  Mic,
  Volume2,
  VolumeX,
  Play,
  Pause,
  Square,
  Circle,
  Triangle,
  Bookmark,
  Flag,
  Award,
  Crown,
  Target,
  Crosshair,
  Compass,
  Navigation,
  Map,
  Truck,
  Box,
  Archive,
  Database,
  Server,
  Cloud,
  Wifi,
  WifiOff,
  Bluetooth,
  Battery,
  Power,
  Cpu,
  Monitor,
  Tablet,
  Watch,
  Headphones,
  Speaker,
  Radio,
  Tv,
  Gamepad,
  Music,
  Film,
  Scissors,
  Wand2,
  Palette,
  Brush,
  PenTool,
  Type,
  Bold,
  Italic,
  Underline,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Columns,
  Rows,
  Table,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Terminal,
  Code,
  Braces,
  Bug,
  Lightbulb,
  Flame,
  Droplet,
  Wind,
  Sun,
  Moon,
  CloudRain,
  Snowflake,
  Thermometer,
  Umbrella,
  Coffee,
  Beer,
  Pizza,
  Apple,
  Banana,
  Carrot,
  Cake,
  Candy,
  Leaf,
  Trees,
  Flower,
  Sprout,
  Feather,
  Bird,
  Fish,
  Cat,
  Dog,
  Rabbit,
  Turtle,
  Footprints,
  Baby,
  PersonStanding,
  Accessibility,
  Activity,
  Ambulance,
  Stethoscope,
  Pill,
  Syringe,
  Dna,
  Atom,
  Microscope,
  Beaker,
  FlaskConical,
  Magnet,
  Scale,
  Ruler,
  Wrench,
  Hammer,
  Screwdriver,
  Paintbrush,
  Scissors as ScissorsIcon,
  Eraser,
  Highlighter,
  Stamp,
  Crop,
  Move,
  Maximize,
  Minimize,
  ZoomIn,
  ZoomOut,
  RotateCw,
  RotateCcw,
  FlipHorizontal,
  FlipVertical,
  type LucideIcon,
} from 'lucide-react';

// Mapping of Ionicons names to Lucide icons
const iconMap: Record<string, LucideIcon> = {
  // Navigation & Layout
  'grid-outline': LayoutGrid,
  'grid': LayoutGrid,
  'home-outline': Home,
  'home': Home,
  'menu-outline': Menu,
  'menu': Menu,
  
  // Commerce & Sales
  'cart-outline': ShoppingCart,
  'cart': ShoppingCart,
  'receipt-outline': Receipt,
  'receipt': Receipt,
  'storefront-outline': Store,
  'storefront': Store,
  'pricetag-outline': Tag,
  'pricetag': Tag,
  'cash-outline': DollarSign,
  'cash': DollarSign,
  'card-outline': CreditCard,
  'card': CreditCard,
  'wallet-outline': Wallet,
  'wallet': Wallet,
  
  // People & Users
  'people-outline': Users,
  'people': Users,
  'person-outline': UserCircle,
  'person': UserCircle,
  'person-add-outline': UserCircle,
  'person-add': UserCircle,
  'people-circle-outline': Users,
  'people-circle': Users,
  
  // Products & Inventory
  'cube-outline': Package,
  'cube': Package,
  'layers-outline': Layers,
  'layers': Layers,
  'folder-outline': FolderOpen,
  'folder': FolderOpen,
  'archive-outline': Archive,
  'archive': Archive,
  'box': Box,
  
  // Analytics & Reports
  'bar-chart-outline': BarChart3,
  'bar-chart': BarChart3,
  'stats-chart-outline': BarChart3,
  'stats-chart': BarChart3,
  'trending-up-outline': TrendingUp,
  'trending-up': TrendingUp,
  'trending-down-outline': TrendingDown,
  'trending-down': TrendingDown,
  
  // Settings & Admin
  'settings-outline': Settings,
  'settings': Settings,
  'shield-outline': Shield,
  'shield': Shield,
  'shield-checkmark-outline': Shield,
  'shield-checkmark': Shield,
  
  // Communication
  'mail-outline': Mail,
  'mail': Mail,
  'chatbubble-outline': MessageSquare,
  'chatbubble': MessageSquare,
  'notifications-outline': Bell,
  'notifications': Bell,
  'send-outline': Send,
  'send': Send,
  'call-outline': Phone,
  'call': Phone,
  'phone-portrait-outline': Smartphone,
  'phone-portrait': Smartphone,
  
  // Actions
  'add-outline': Plus,
  'add': Plus,
  'add-circle-outline': PlusCircle,
  'add-circle': PlusCircle,
  'remove-outline': Minus,
  'remove': Minus,
  'remove-circle-outline': MinusCircle,
  'remove-circle': MinusCircle,
  'close-outline': X,
  'close': X,
  'close-circle-outline': XCircle,
  'close-circle': XCircle,
  'checkmark-outline': CheckCircle,
  'checkmark': CheckCircle,
  'checkmark-circle-outline': CheckCircle,
  'checkmark-circle': CheckCircle,
  'trash-outline': Trash2,
  'trash': Trash2,
  'create-outline': Edit,
  'create': Edit,
  'pencil-outline': Edit,
  'pencil': Edit,
  'search-outline': Search,
  'search': Search,
  'filter-outline': Filter,
  'filter': Filter,
  'refresh-outline': Refresh,
  'refresh': Refresh,
  'download-outline': Download,
  'download': Download,
  'upload-outline': Upload,
  'cloud-upload-outline': Upload,
  'cloud-download-outline': Download,
  'print-outline': Printer,
  'print': Printer,
  'copy-outline': Copy,
  'copy': Copy,
  'share-outline': Share2,
  'share': Share2,
  'share-social-outline': Share2,
  'share-social': Share2,
  'link-outline': Link,
  'link': Link,
  'open-outline': ExternalLink,
  'open': ExternalLink,
  
  // Navigation arrows
  'chevron-forward-outline': ChevronRight,
  'chevron-forward': ChevronRight,
  'chevron-back-outline': ChevronLeft,
  'chevron-back': ChevronLeft,
  'chevron-down-outline': ChevronDown,
  'chevron-down': ChevronDown,
  'chevron-up-outline': ChevronUp,
  'chevron-up': ChevronUp,
  'arrow-forward-outline': ArrowRight,
  'arrow-forward': ArrowRight,
  'arrow-back-outline': ArrowLeft,
  'arrow-back': ArrowLeft,
  'arrow-up-outline': ArrowUp,
  'arrow-up': ArrowUp,
  'arrow-down-outline': ArrowDown,
  'arrow-down': ArrowDown,
  
  // Status & Alerts
  'alert-circle-outline': AlertCircle,
  'alert-circle': AlertCircle,
  'warning-outline': AlertCircle,
  'warning': AlertCircle,
  'information-circle-outline': Info,
  'information-circle': Info,
  'help-circle-outline': HelpCircle,
  'help-circle': HelpCircle,
  
  // Auth & Security
  'lock-closed-outline': Lock,
  'lock-closed': Lock,
  'lock-open-outline': Lock,
  'lock-open': Lock,
  'eye-outline': Eye,
  'eye': Eye,
  'eye-off-outline': EyeOff,
  'eye-off': EyeOff,
  'log-out-outline': LogOut,
  'log-out': LogOut,
  'log-in-outline': LogOut,
  'log-in': LogOut,
  
  // Time & Calendar
  'time-outline': Clock,
  'time': Clock,
  'calendar-outline': Calendar,
  'calendar': Calendar,
  
  // Location
  'location-outline': MapPin,
  'location': MapPin,
  'map-outline': Map,
  'map': Map,
  'globe-outline': Globe,
  'globe': Globe,
  'navigate-outline': Navigation,
  'navigate': Navigation,
  'compass-outline': Compass,
  'compass': Compass,
  'business-outline': Building,
  'business': Building,
  
  // Documents
  'document-outline': FileText,
  'document': FileText,
  'document-text-outline': FileText,
  'document-text': FileText,
  'clipboard-outline': FileText,
  'clipboard': FileText,
  
  // Media
  'image-outline': Image,
  'image': Image,
  'camera-outline': Camera,
  'camera': Camera,
  'videocam-outline': Video,
  'videocam': Video,
  'mic-outline': Mic,
  'mic': Mic,
  'volume-high-outline': Volume2,
  'volume-high': Volume2,
  'volume-mute-outline': VolumeX,
  'volume-mute': VolumeX,
  'play-outline': Play,
  'play': Play,
  'pause-outline': Pause,
  'pause': Pause,
  'stop-outline': Square,
  'stop': Square,
  
  // Social & Engagement
  'heart-outline': Heart,
  'heart': Heart,
  'star-outline': Star,
  'star': Star,
  'bookmark-outline': Bookmark,
  'bookmark': Bookmark,
  'flag-outline': Flag,
  'flag': Flag,
  'gift-outline': Gift,
  'gift': Gift,
  'trophy-outline': Award,
  'trophy': Award,
  'ribbon-outline': Award,
  'ribbon': Award,
  
  // More
  'ellipsis-horizontal-outline': MoreHorizontal,
  'ellipsis-horizontal': MoreHorizontal,
  'ellipsis-vertical-outline': MoreVertical,
  'ellipsis-vertical': MoreVertical,
  'options-outline': Settings,
  'options': Settings,
  
  // Misc
  'flash-outline': Zap,
  'flash': Zap,
  'bulb-outline': Lightbulb,
  'bulb': Lightbulb,
  'flame-outline': Flame,
  'flame': Flame,
  'water-outline': Droplet,
  'water': Droplet,
  'sunny-outline': Sun,
  'sunny': Sun,
  'moon-outline': Moon,
  'moon': Moon,
  'cloud-outline': Cloud,
  'cloud': Cloud,
  'rainy-outline': CloudRain,
  'rainy': CloudRain,
  'snow-outline': Snowflake,
  'snow': Snowflake,
  'thermometer-outline': Thermometer,
  'thermometer': Thermometer,
  'cafe-outline': Coffee,
  'cafe': Coffee,
  'pizza-outline': Pizza,
  'pizza': Pizza,
  'leaf-outline': Leaf,
  'leaf': Leaf,
  
  // Tech & Devices
  'wifi-outline': Wifi,
  'wifi': Wifi,
  'bluetooth-outline': Bluetooth,
  'bluetooth': Bluetooth,
  'battery-full-outline': Battery,
  'battery-full': Battery,
  'power-outline': Power,
  'power': Power,
  'desktop-outline': Monitor,
  'desktop': Monitor,
  'tablet-portrait-outline': Tablet,
  'tablet-portrait': Tablet,
  'watch-outline': Watch,
  'watch': Watch,
  'headset-outline': Headphones,
  'headset': Headphones,
  'radio-outline': Radio,
  'radio': Radio,
  'tv-outline': Tv,
  'tv': Tv,
  'game-controller-outline': Gamepad,
  'game-controller': Gamepad,
  'musical-notes-outline': Music,
  'musical-notes': Music,
  'film-outline': Film,
  'film': Film,
  
  // Dev & Code
  'terminal-outline': Terminal,
  'terminal': Terminal,
  'code-outline': Code,
  'code': Code,
  'git-branch-outline': GitBranch,
  'git-branch': GitBranch,
  'git-commit-outline': GitCommit,
  'git-commit': GitCommit,
  'git-merge-outline': GitMerge,
  'git-merge': GitMerge,
  'git-pull-request-outline': GitPullRequest,
  'git-pull-request': GitPullRequest,
  'bug-outline': Bug,
  'bug': Bug,
  
  // Health
  'fitness-outline': Activity,
  'fitness': Activity,
  'pulse-outline': Activity,
  'pulse': Activity,
  'medkit-outline': Stethoscope,
  'medkit': Stethoscope,
  
  // Construction & Tools
  'construct-outline': Wrench,
  'construct': Wrench,
  'hammer-outline': Hammer,
  'hammer': Hammer,
  'build-outline': Wrench,
  'build': Wrench,
  'cut-outline': Scissors,
  'cut': Scissors,
  'color-palette-outline': Palette,
  'color-palette': Palette,
  'brush-outline': Brush,
  'brush': Brush,
  
  // Shapes
  'square-outline': Square,
  'square': Square,
  'triangle-outline': Triangle,
  'triangle': Triangle,
  'ellipse-outline': Circle,
  'ellipse': Circle,
  
  // Transform
  'resize-outline': Maximize,
  'resize': Maximize,
  'expand-outline': Maximize,
  'expand': Maximize,
  'contract-outline': Minimize,
  'contract': Minimize,
  'scan-outline': Crosshair,
  'scan': Crosshair,
  'qr-code-outline': Grid,
  'qr-code': Grid,
  'barcode-outline': List,
  'barcode': List,
};

interface IconProps {
  name: string;
  size?: number;
  color?: string;
  style?: any;
}

export const Icon: React.FC<IconProps> = ({ name, size = 24, color = '#6B7280', style }) => {
  // On web, use Lucide icons (they work reliably)
  if (Platform.OS === 'web') {
    const LucideComponent = iconMap[name];
    
    if (LucideComponent) {
      return <LucideComponent size={size} color={color} style={style} />;
    }
    
    // Fallback: try to render a generic icon or return null
    console.warn(`Icon "${name}" not found in lucide mapping, falling back`);
    return <Package size={size} color={color} style={style} />;
  }
  
  // On native platforms, use Ionicons (they work there)
  return <Ionicons name={name as any} size={size} color={color} style={style} />;
};

export default Icon;
